### ISSUE TITLE
Refactor front end interactivity related code to js 

### ISSUE THREAD

**Issue by 1233iughe** [1233iughe/emotional_diary#10]
# Details
 All functionality that involves updating the UI in any way depends on loading an updated template from the server. This is to inefficient and will not escalate well.

# TODO
1. Update 'emotion management ' screen to do the UI changes locally on client-side instead of server side using js.
2. Update 'home' screen to to do the UI changes locally on client-side instead of server side using js.

**Comment by 1233iughe** [comment]
# "emotion_management" view refactoring 

## Deadline: 

TODO:
- [x] Change name of route "manage_emotions" to "add_emotion"
- [ ] Add rows with emotion-color pairs using js
- [ ] Send POST request to server with the info of the emotion color pair as a dictionary {"emotion": "x", "color":hex}
- [ ] Update database "settings"
- [ ] Eliminate rows using "delete" button (js)
- [ ] Send POST request to server with the info of the emotion color pair as a dictionary {"emotion": "x", "color":hex}
- [ ] Update database "settings"

**Comment by 1233iughe** [comment]
Completed prototype for functionality on mock server
